### PR TITLE
fix: treat addMember failure as fatal during account creation

### LINKED ISSUE #409: Admin roster: addMember failure silently swallowed during account creation
## Bug

When an admin creates a new user through the roster, `RosterTable.tsx` calls `authClient.admin.createUser()` then `authClient.organization.addMember()`. If `addMember()` fails, the code shows a warning toast but then immediately shows a success toast (`Account created successfully`), hiding the warning. The admin has no indication that the user wasn't added to the organization.

A user who isn't in the organization can't have their role changed, email updated, or be managed through the roster's admin controls. The admin sees "Account created successfully" and only discovers the problem when they try to change the user's role and nothing happens.

Similarly, if the organization ID isn't configured (`NEXT_PUBLIC_APP_ORGANIZATION` not set), the code silently creates the user without org membership and shows success.

## Root cause

`RosterTable.tsx` lines 155-164 treat `addMember()` failure as non-fatal:

```typescript
if (addMemberResult.error) {
  console.error("Failed to add user to organization:", addMemberResult.error);
  toast.warning("...");  // Immediately covered by success toast below
}
// ...
toast.success(`Account created successfully for ${newAccount.username}`);
```

## Fix

Make `addMember()` failure and missing organization ID fatal by throwing, so the catch block handles them with `toast.error()`.

## Discovery

Found while investigating E2E test failures in #394 — role-modification tests that create temp users and then change their roles would see no success toast after the role change. The root cause was that `addMember()` was failing during account creation but the success toast masked the error, leaving the user without organization membership. The subsequent `resolveMemberId()` call in the role-change path would throw "User is not a member of the organization."

### PR DESCRIPTION
**Pull request by jakebromberg**
Closes #409

## Summary

- Make `addMember()` failure throw instead of showing a warning toast that gets immediately covered by the success toast
- Make missing organization ID throw instead of silently creating users without org membership
- Add unit tests for account creation error handling (`RosterTable.test.tsx`)

## Context

When an admin creates a new user through the roster, `addMember()` failure was silently swallowed — the admin saw "Account created successfully" but the user wasn't added to the organization. This meant role changes, email updates, and other admin operations would silently fail because `resolveMemberId()` couldn't find the user in the organization member list.

Discovered while investigating E2E failures in #394 — role-modification tests that create temp users and then change their roles would see no success toast after the role change.

## Test plan

- [ ] Unit tests pass: `npx vitest run src/components/experiences/modern/admin/roster/__tests__/RosterTable.test.tsx`
- [ ] Full test suite passes: `npm run test:run`
- [ ] Manual: create a user in the roster — verify success toast appears
- [ ] Manual: if `addMember` fails (e.g., disconnect backend mid-request) — verify error toast appears instead of success

### CODE REVIEW

**Comment by jakebromberg** [comment]
Superseded by #415 which replaces the entire createUser + addMember flow with a single provision-user endpoint call, eliminating the addMember failure mode entirely.
