### ISSUE TITLE
Admin roster: addMember failure silently swallowed during account creation

### ISSUE THREAD

**Issue by jakebromberg** [WXYC/dj-site#409]
## Bug

When an admin creates a new user through the roster, `RosterTable.tsx` calls `authClient.admin.createUser()` then `authClient.organization.addMember()`. If `addMember()` fails, the code shows a warning toast but then immediately shows a success toast (`Account created successfully`), hiding the warning. The admin has no indication that the user wasn't added to the organization.

A user who isn't in the organization can't have their role changed, email updated, or be managed through the roster's admin controls. The admin sees "Account created successfully" and only discovers the problem when they try to change the user's role and nothing happens.

Similarly, if the organization ID isn't configured (`NEXT_PUBLIC_APP_ORGANIZATION` not set), the code silently creates the user without org membership and shows success.

## Root cause

`RosterTable.tsx` lines 155-164 treat `addMember()` failure as non-fatal:

```typescript
if (addMemberResult.error) {
  console.error("Failed to add user to organization:", addMemberResult.error);
  toast.warning("...");  // Immediately covered by success toast below
}
// ...
toast.success(`Account created successfully for ${newAccount.username}`);
```

## Fix

Make `addMember()` failure and missing organization ID fatal by throwing, so the catch block handles them with `toast.error()`.

## Discovery

Found while investigating E2E test failures in #394 — role-modification tests that create temp users and then change their roles would see no success toast after the role change. The root cause was that `addMember()` was failing during account creation but the success toast masked the error, leaving the user without organization membership. The subsequent `resolveMemberId()` call in the role-change path would throw "User is not a member of the organization."

**Comment by jakebromberg** [comment]
Resolved by WXYC/Backend-Service#419 (provision-user endpoint bypasses broken addMember) and #415 (dj-site integration). The root cause was a better-auth bug: the addMember endpoint handler was defined but never registered on the router, so it always returned 404.
